In [9]:
import numpy as np

In [10]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1



array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.empty((2, 3, 2))

array([[[1.20745126e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 4.28155459e-037]],

       [[1.21075302e-071, 2.93003720e-057],
        [4.32025243e-061, 2.25376624e+184],
        [6.89465336e-042, 3.05937335e-057]]])

In [15]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
arr = np.array(([1.,2.,3.], [4.,5.,6.]))
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [18]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])