In [62]:
%matplotlib inline


In [65]:
import numpy as np
import matplotlib.pyplot as plt

In [67]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [68]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

(2, 4)

In [69]:
arr2.ndim

2

In [70]:
arr2.shape

(2, 4)

In [71]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [73]:
np.empty((2, 3, 2))

array([[[ 0.00000000e+000, -1.28822984e-231],
        [ 2.96439388e-323,  0.00000000e+000],
        [ 7.19999695e+000,  5.74084271e+169]],

       [[ 5.49816892e-090,  2.42259129e-052],
        [ 1.53450533e-052,  2.37816580e+184],
        [ 3.99910963e+252,  8.34402697e-309]]])

In [74]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
np.arange(15).reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names


array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [80]:
data = np.random.randn(7, 4)
data

array([[-0.84783939, -0.46921765,  1.25806661, -1.44620836],
       [ 0.59953641,  0.34520437,  0.34994419, -1.01955451],
       [ 0.43137651, -0.16564754,  0.38621418,  1.36944799],
       [-1.2635767 ,  0.30533173,  0.92340174,  0.63315785],
       [ 0.9536034 , -0.79600172, -1.59778312, -0.87011174],
       [-1.13531111,  0.14756084, -0.62404222,  0.22952812],
       [-1.03424114,  0.72512311, -0.33163447,  0.6346885 ]])

In [82]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [84]:
data[names == 'Bob']

array([[-0.84783939, -0.46921765,  1.25806661, -1.44620836],
       [-1.2635767 ,  0.30533173,  0.92340174,  0.63315785]])

In [85]:
data[names == 'Bob', 2:]

array([[ 1.25806661, -1.44620836],
       [ 0.92340174,  0.63315785]])

In [87]:
data[names == 'Bob', 3]

array([-1.44620836,  0.63315785])

In [91]:
data[names != 'Bob']

array([[ 0.59953641,  0.34520437,  0.34994419, -1.01955451],
       [ 0.43137651, -0.16564754,  0.38621418,  1.36944799],
       [ 0.9536034 , -0.79600172, -1.59778312, -0.87011174],
       [-1.13531111,  0.14756084, -0.62404222,  0.22952812],
       [-1.03424114,  0.72512311, -0.33163447,  0.6346885 ]])

In [94]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-0.84783939, -0.46921765,  1.25806661, -1.44620836],
       [ 0.43137651, -0.16564754,  0.38621418,  1.36944799],
       [-1.2635767 ,  0.30533173,  0.92340174,  0.63315785],
       [ 0.9536034 , -0.79600172, -1.59778312, -0.87011174]])

In [97]:
data[data < 0] = 0
data

array([[0.        , 0.        , 1.25806661, 0.        ],
       [0.59953641, 0.34520437, 0.34994419, 0.        ],
       [0.43137651, 0.        , 0.38621418, 1.36944799],
       [0.        , 0.30533173, 0.92340174, 0.63315785],
       [0.9536034 , 0.        , 0.        , 0.        ],
       [0.        , 0.14756084, 0.        , 0.22952812],
       [0.        , 0.72512311, 0.        , 0.6346885 ]])

In [98]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.59953641, 0.34520437, 0.34994419, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.14756084, 0.        , 0.22952812],
       [0.        , 0.72512311, 0.        , 0.6346885 ]])